name: Generate Jars
on: [ push, pull_request ]
jobs:
  paperclip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build Paperclip jar
        run: ./gradlew createReobfPaperclipJar --stacktrace
      - name: Upload Paperclip jar
        uses: actions/upload-artifact@v2
        with:
          name: multipaper.jar
          path: build/libs/MultiPaper-paperclip-*-reobf.jar
  multipaper-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Package MultiPaper-Master jar
        working-directory: ./MultiPaper-Master
        run: mvn package
      - name: Upload MultiPaper-Master jar
        uses: actions/upload-artifact@v2
        with:
          name: multipaper-master.jar
          path: MultiPaper-Master/target/multipaper-master*.jar